"""schema inicial em uuid

Revision ID: 479b68257986
Revises: 
Create Date: 2026-09-07 15:31:34.833424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '479b68257986'
down_revision = None
branch_labels = None
depends_on = None


TIPOS_ENUMERADOS = (
    postgresql.ENUM('enviado', 'falha', name='email_situacao_enum'),
    postgresql.ENUM('pendente', 'aprovada', 'recusada', name='solicitacao_situacao_enum'),
    postgresql.ENUM('conferencia', 'periodico', 'chamada_interna', 'outro', name='evento_tipo_enum'),
    postgresql.ENUM('pendente_aprovacao', 'aprovado', 'publicado', 'encerrado', name='evento_situacao_enum'),
    postgresql.ENUM('aberta', 'simples_cega', 'duplo_cega', name='modelo_avaliacao_enum'),
    postgresql.ENUM('avaliacao', 'participacao', name='convite_tipo_enum'),
    postgresql.ENUM('chair', 'avaliador', 'responsavel_etapa', name='papel_enum'),
    postgresql.ENUM('pendente', 'aceito', 'expirado', name='convite_situacao_enum'),
)


def upgrade():
    # `uuid_generate_v4()` e o default de toda chave primaria (AD-004).
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    for tipo in TIPOS_ENUMERADOS:
        tipo.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_enviados',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('situacao', postgresql.ENUM('enviado', 'falha', name='email_situacao_enum', create_type=False), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tentativas_login',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.create_index('ix_tentativas_login_email_ocorrido_em', ['email', sa.literal_column('ocorrido_em DESC')], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('identificador_orcid', sa.String(length=30), nullable=True),
    sa.Column('administrador', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('familia', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotacionado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index('ix_sessoes_familia', ['familia'], unique=False)

    op.create_table('solicitacoes_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('situacao', postgresql.ENUM('pendente', 'aprovada', 'recusada', name='solicitacao_situacao_enum', create_type=False), server_default='pendente', nullable=False),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_recusa', sa.Text(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('identificador_pagina', sa.String(length=100), nullable=False),
    sa.Column('tipo', postgresql.ENUM('conferencia', 'periodico', 'chamada_interna', 'outro', name='evento_tipo_enum', create_type=False), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('fuso', sa.String(length=60), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('evento_pai_id', sa.UUID(), nullable=True),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_pagina')
    )
    op.create_table('tokens_confirmacao_email',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('tokens_confirmacao_email', schema=None) as batch_op:
        batch_op.create_index('ix_tokens_confirmacao_email_usuario_criado_em', ['usuario_id', sa.literal_column('criado_em DESC')], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=True),
    sa.Column('situacao', postgresql.ENUM('pendente_aprovacao', 'aprovado', 'publicado', 'encerrado', name='evento_situacao_enum', create_type=False), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('identificador_pagina', sa.String(length=100), nullable=False),
    sa.Column('tipo', postgresql.ENUM('conferencia', 'periodico', 'chamada_interna', 'outro', name='evento_tipo_enum', create_type=False), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('fuso', sa.String(length=60), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('evento_pai_id', sa.UUID(), nullable=True),
    sa.Column('modelo_avaliacao', postgresql.ENUM('aberta', 'simples_cega', 'duplo_cega', name='modelo_avaliacao_enum', create_type=False), server_default='aberta', nullable=False),
    sa.Column('avaliadores_por_submissao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rebuttal_habilitado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('prazo_rebuttal_dias', sa.Integer(), nullable=True),
    sa.Column('maximo_rodadas', sa.Integer(), server_default='1', nullable=False),
    sa.Column('nota_corte', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('limite_submissoes_por_autor', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT rebuttal_habilitado OR prazo_rebuttal_dias IS NOT NULL', name='ck_eventos_rebuttal_com_prazo'),
    sa.CheckConstraint('avaliadores_por_submissao >= 1', name='ck_eventos_avaliadores_por_submissao'),
    sa.CheckConstraint('maximo_rodadas >= 1', name='ck_eventos_maximo_rodadas'),
    sa.ForeignKeyConstraint(['evento_pai_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_evento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_pagina')
    )
    op.create_foreign_key(
        'fk_solicitacoes_evento_evento_pai_id',
        'solicitacoes_evento',
        'eventos',
        ['evento_pai_id'],
        ['id'],
    )
    op.create_table('solicitacao_chairs_iniciais',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitacao_id', 'email', name='uq_solicitacao_chairs_iniciais_email')
    )
    op.create_table('convites',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('tipo', postgresql.ENUM('avaliacao', 'participacao', name='convite_tipo_enum', create_type=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=True),
    sa.Column('papel', postgresql.ENUM('chair', 'avaliador', 'responsavel_etapa', name='papel_enum', create_type=False), nullable=True),
    sa.Column('submissao_id', sa.UUID(), nullable=True),
    sa.Column('prazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contato_organizacao', sa.String(length=255), nullable=True),
    sa.Column('situacao', postgresql.ENUM('pendente', 'aceito', 'expirado', name='convite_situacao_enum', create_type=False), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aceito_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo <> 'avaliacao' OR submissao_id IS NOT NULL", name='ck_convites_avaliacao_com_submissao'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('criterios_avaliacao',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nota_minima', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota_maxima', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nota_maxima > nota_minima', name='ck_criterios_avaliacao_faixa_de_nota'),
    sa.CheckConstraint('peso > 0', name='ck_criterios_avaliacao_peso'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fases_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacoes_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('papel', postgresql.ENUM('chair', 'avaliador', 'responsavel_etapa', name='papel_enum', create_type=False), nullable=False),
    sa.Column('areas_interesse', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'usuario_id', 'papel', name='uq_participacao_evento_papel')
    )
    op.create_table('trilhas',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'nome', name='uq_trilhas_evento_nome')
    )
    op.create_table('chamadas',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('trilha_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permite_submissao_apos_prazo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('formatos_aceitos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tamanho_maximo_mb', sa.Integer(), nullable=True),
    sa.Column('encerrada_manualmente', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('data_limite > data_abertura', name='ck_chamadas_data_limite_apos_abertura'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_parecer',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('criterio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios_avaliacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formularios_chamada',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('chamada_id', sa.UUID(), nullable=False),
    sa.Column('versao', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['chamada_id'], ['chamadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('chamada_id', sa.UUID(), nullable=False),
    sa.Column('trilha_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chamada_id'], ['chamadas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_solicitacoes_evento_evento_pai_id',
        'solicitacoes_evento',
        type_='foreignkey',
    )
    op.drop_table('submissoes')
    op.drop_table('formularios_chamada')
    op.drop_table('notas_parecer')
    op.drop_table('chamadas')
    op.drop_table('trilhas')
    op.drop_table('participacoes_evento')
    op.drop_table('fases_evento')
    op.drop_table('criterios_avaliacao')
    op.drop_table('convites')
    op.drop_table('solicitacao_chairs_iniciais')
    op.drop_table('eventos')
    with op.batch_alter_table('tokens_confirmacao_email', schema=None) as batch_op:
        batch_op.drop_index('ix_tokens_confirmacao_email_usuario_criado_em')

    op.drop_table('tokens_confirmacao_email')
    op.drop_table('solicitacoes_evento')
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index('ix_sessoes_familia')

    op.drop_table('sessoes')
    op.drop_table('usuarios')
    with op.batch_alter_table('tentativas_login', schema=None) as batch_op:
        batch_op.drop_index('ix_tentativas_login_email_ocorrido_em')

    op.drop_table('tentativas_login')
    op.drop_table('emails_enviados')
    for tipo in TIPOS_ENUMERADOS:
        tipo.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
