"""pedidos de reenvio por email

Revision ID: 9c5cdfd4e774
Revises: 479b68257986
Create Date: 2026-09-07 16:14:03.846292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5cdfd4e774'
down_revision = '479b68257986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_de_reenvio',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos_de_reenvio', schema=None) as batch_op:
        batch_op.create_index('ix_pedidos_de_reenvio_email_criado_em', ['email_hash', sa.literal_column('criado_em DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_reenvio', schema=None) as batch_op:
        batch_op.drop_index('ix_pedidos_de_reenvio_email_criado_em')

    op.drop_table('pedidos_de_reenvio')
    # ### end Alembic commands ###
