"""titulo da submissao no convite

Revision ID: d617d0800afa
Revises: 9c5cdfd4e774
Create Date: 2026-09-07 17:04:00.069388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd617d0800afa'
down_revision = '9c5cdfd4e774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submissao_titulo', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.drop_column('submissao_titulo')

    # ### end Alembic commands ###
